FROM opencode-saas-sandbox-test:v2fix
COPY packages/opencode/src /app/packages/opencode/src
COPY packages/core/src /app/packages/core/src
COPY packages/sdk/js/src/v2/gen /app/packages/sdk/js/src/v2/gen
COPY packages/tui/src /app/packages/tui/src
RUN chown -R opencode:opencode /app/packages
