export * as SessionDerive from "./derive.js"

import { DateTime, Effect } from "effect"
import type { SessionMessage } from "@opencode/schema/session-message"
import type { SessionSchema } from "./schema.js"
import type { SessionStore } from "./store.js"

const MAX_CONVERSATION_CHARS = 96_000

/**
 * Serializes a source session for summaryFrom derivation (v1 plan C): the
 * latest completed compaction never supplies output text — it only anchors the
 * input — and the transcript is rebuilt from the message events after it. The
 * derived summary is always freshly generated by the new session's own
 * compaction run; the source session is never written.
 *
 * `undefined` means there is nothing worth summarizing (no user message, or
 * neither anchor text nor conversation), matching v1's silent skip.
 */
export const transcript = Effect.fn("SessionDerive.transcript")(function* (
  store: Effect.Success<typeof SessionStore.Service>,
  source: SessionSchema.ID,
) {
  // store.messages returns newest-first; the anchor walk needs oldest-first.
  const messages = (yield* store.messages({ sessionID: source }).pipe(Effect.orElseSucceed(() => []))).toSorted(
    (left, right) => DateTime.toEpochMillis(left.time.created) - DateTime.toEpochMillis(right.time.created),
  )
  if (!messages.some((message) => message.type === "user")) return undefined

  const anchorIndex = messages.findLastIndex(
    (message) => message.type === "compaction" && message.status === "completed",
  )
  const anchor = anchorIndex >= 0 ? messages[anchorIndex] : undefined
  const recent = anchor ? messages.slice(anchorIndex + 1) : messages
  const conversation = recent.flatMap(serializeMessage).join("\n\n").slice(0, MAX_CONVERSATION_CHARS)
  const priorSummary =
    anchor?.type === "compaction" && anchor.status === "completed" ? anchor.summary.trim() : undefined
  if (!conversation && !priorSummary) return undefined

  return [
    ...(priorSummary ? [`<prior-summary>\n${priorSummary}\n</prior-summary>`] : []),
    ...(conversation ? [`<conversation>\n${conversation}\n</conversation>`] : []),
  ].join("\n\n")
})

function serializeMessage(message: SessionMessage.Info): ReadonlyArray<string> {
  if (message.type === "user") {
    const text = message.text?.trim()
    return text ? [`User: ${text}`] : []
  }
  if (message.type === "assistant") {
    return message.content.flatMap((part): ReadonlyArray<string> => {
      if (part.type === "text") {
        const text = part.text.trim()
        return text ? [`Assistant: ${text}`] : []
      }
      // Tool calls/results carry facts the next agent needs (v1 SUM-7): keep the
      // call and its output in the transcript, not just assistant prose.
      return part.type === "tool" ? serializeTool(part) : []
    })
  }
  if (message.type === "synthetic") {
    const text = message.text.trim()
    return text ? [`User: ${text}`] : []
  }
  return []
}

function serializeTool(part: SessionMessage.AssistantTool): ReadonlyArray<string> {
  const call = `Assistant tool ${part.name}`
  if (part.state.status === "streaming") return [`${call}(...)`]
  const header = `${call}(${JSON.stringify(part.state.input)})`
  if (part.state.status === "completed") {
    const output = toolText(part.state.content)
    return [output ? `${header} ->\n${output}` : header]
  }
  if (part.state.status === "error") {
    const output = toolText(part.state.content ?? [])
    return [`${header} ->\nerror: ${output || part.state.error.message}`]
  }
  return [header]
}

function toolText(content: ReadonlyArray<{ readonly type: string; readonly text?: string }>): string {
  return content.flatMap((item) => (item.type === "text" && item.text?.trim() ? [item.text.trim()] : [])).join("\n")
}
