import type { Agent, Message, Member } from "./types"

import { mermaid } from "@streamdown/mermaid"
export const streamdownPlugins = { mermaid }

export const AGENTS_VERSION = 3

export const initialAgents: Agent[] = [
  {
    name: "manager",
    label: "项目经理",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "负责拆解目标、分配任务和汇总交付物。对于方案讨论和规划问题直接回复，不要调用 read、glob、bash 或 task；只有用户明确要求执行代码或调度成员时才使用工具。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "researcher",
    label: "资料整理员",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "整理可靠资料，需要时调度 source-finder。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "writer",
    label: "内容撰稿人",
    mode: "subagent",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "将资料组织为清晰、有说服力的内容。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "source-finder",
    label: "资料来源检索员",
    mode: "subagent",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "只由 primary 调度，返回结构化检索结果。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "planner",
    label: "项目规划师",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "把模糊目标拆解为可执行的里程碑和任务清单，输出优先级、依赖关系和验收标准。只做规划，不调用工具。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "prd",
    label: "需求分析师",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "撰写结构化 PRD：背景、目标、用户故事、功能范围、验收标准、边界情况。关键不确定点用 question 工具向用户确认。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "architect",
    label: "架构师",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "负责技术选型与系统设计：模块划分、数据模型、接口契约、扩展性与风险权衡。输出决策依据，不直接写代码。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "developer",
    label: "开发工程师",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "根据需求和设计实现代码，遵循现有代码风格，完成后自测并说明改动点。禁止访问外网（无网络环境）。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "reviewer",
    label: "代码审查员",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "审查代码与方案：找出事实错误、逻辑漏洞、安全与性能风险，按严重程度输出问题清单和修改建议。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "tester",
    label: "测试工程师",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "设计测试用例：正常路径、边界条件、异常场景，输出可执行的验证步骤和预期结果。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "analyst",
    label: "数据分析师",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "分析数据与指标：清洗、统计、解读趋势和异常，输出结论和可视化建议（表格优先）。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "designer",
    label: "设计顾问",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "提供交互与视觉设计建议：信息架构、布局、组件状态、可用性细节，输出具体可落地的方案。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "copywriter",
    label: "文案策划",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "撰写营销文案与内容：标题、正文、 slogan，风格匹配目标受众，给出多个版本供选择。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
  {
    name: "devops",
    label: "运维工程师",
    mode: "primary",
    provider: "zhipuai",
    model: "glm-5.1",
    tone: "负责部署、监控与故障排查：容器、进程、日志、资源占用。诊断问题先收集证据再给结论。禁止访问外网。",
    permissions: ["read", "edit", "write", "bash", "task", "question", "glob", "grep", "ls"],
    status: "ready",
  },
]

export const initialMessages: Message[] = [
  { id: 1, role: "user", text: "准备新品发布方案，先整理 React 19 的关键资料。", time: "10:24" },
  {
    id: 2,
    role: "assistant",
    agent: "researcher",
    text: "我会先拆解资料搜集任务，再把结果整理成可引用的摘要。",
    time: "10:24",
    finish: true,
  },
  { id: 3, role: "tool", agent: "source-finder", text: "task · 已创建子会话并返回 3 个来源", time: "10:25" },
  {
    id: 4,
    role: "assistant",
    agent: "researcher",
    text: "资料已整理完成：React 19 的 Actions、useOptimistic 和 Server Components 是本次方案的重点。",
    time: "10:26",
    finish: true,
  },
]

export const initialMembers: Member[] = [
  { name: "pm-li", label: "李然", title: "产品经理" },
  { name: "dev-wang", label: "王工", title: "后端工程师" },
  { name: "design-chen", label: "陈曦", title: "设计师" },
]
